spring.application.name=jirapobre
spring.datasource.url=jdbc:postgresql://aws-1-us-east-1.pooler.supabase.com:6543/postgres?sslmode=require&preferQueryMode=simple
spring.datasource.username=postgres.nbrkcbuzofiqpgetuqzy
spring.datasource.password=JoyBoy30M?!
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
server.port=8082
jwt.secret=ec6127bb4ee33ef91a86802d00ec2574f324daab8866d1e1758a0a251743fd3face815f92822ff62ec722880fc9091f6240d047786aabc15d633502c69d2c49c
jwt.expiration=86400000
springdoc.api-docs.enabled=true
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.enabled=false
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true
service.secret-key=eeef77bfe9fabd437e22a4d2764b63913778068d37b884504e349c89d235908c71ba8a2ac082d1791e64b0c3032eade9a2f70e615dc7a6a31230becf5277e521
